version: '3.8'

services:
  frontend:
    build:
      context: ./client
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build:
      context: ./server
    ports:
      - "3000:3000"
    env_file:
      - .env
